# ---------------- #
#   Main Configs   #
# ---------------- #
title: 刘华超
subtitle: 刘华超的个人博客
description: 刘华超的个人博客
keywords: 刘华超, 博客，blog，Github
url: "http://www.liuhuachao.com/blog"
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: liuhuachao
organization: http://www.liuhuachao.com
organization_url: http://www.liuhuachao.com
github_username: liuhuachao
location: Shenzhen, China
email: liuhuachao@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: blog/liuhuachao.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: disqus_lhc
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: liuhuachao
    repo: blog
    oauth:
        client_id: f8a28a04e8e2ee919e8f
        client_secret: aee4fe6feac92961ae0ffc1393f1ee1f4126e9d0 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: liuhuachao
    repo: blog
    client_id: f8a28a04e8e2ee919e8f
    client_secret: aee4fe6feac92961ae0ffc1393f1ee1f4126e9d0 

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1